### ISSUE TITLE
Error Installing via composer

### ISSUE THREAD

**Issue by rubahjantan** [dlds/yii2-intercooler#1]
i tried to install yii2-intercooler 2.2 and facing with this error 
dlds/yii2-intercooler 2.2 requires bower-asset/intercooler-js ~0.9.4 -> no matching package found
i have added bower-asset/intercooler-js ~0.9.4 in composer.json require. It seem the intercooler asset already removed.

**Comment by jirisvoboda** [comment]
Hi,

I think I don't understand your issue well. 

bower-asset/intercooler-js ~0.9.4 is already added in composer.json file of this vendor. So it should be installed automatically.

One question came to my mind: 

Do you have your bower lib set properly? I mean - does any other bower lib install right?

**Comment by rubahjantan** [comment]
hi too, sorry for my bad english,
any other bower lib like "bower-asset/jquery": "@stable", installed succesfully, 
here is my error when running composer update
- The requested package bower-asset/intercooler-js could not be found in any version, there may be a typo in the package name.
  Problem 2
  - dlds/yii2-intercooler 2.2 requires bower-asset/intercooler-js ~0.9.4 -> no matching package found

**Comment by rubahjantan** [comment]
It solved, sorry i forget to run php composer.phar global require "fxp/composer-asset-plugin:~1.1.1"
